package Vista;

import java.net.URL;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;

/**
 * UI dedicada a la seleccion del idioma en el que va a ser visualizada toda la
 * aplicacion.
 *
 * @author Angel Flores
 *
 */
public class SelectorLenguaje extends javax.swing.JFrame {

    String[] idiomas = {"Galego", "Español"};

    /**
     * Creates new form Login
     */
    public SelectorLenguaje() {
        initComponents();
        
        //activarAyuda();
        for (String idioma : idiomas) {
            cmbIdiomas.addItem(idioma);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        lblSeleccionaIdioma = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        cmbIdiomas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleción de idioma");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(257, 150));

        lblSeleccionaIdioma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSeleccionaIdioma.setText("Selecciona un idioma");

        btnAceptar.setBackground(new java.awt.Color(66,66,66));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSeleccionaIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbIdiomas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblSeleccionaIdioma)
                .addGap(18, 18, 18)
                .addComponent(cmbIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }

    /**
     * Metodo ejecutado cuando se pulsa sobre el boton de aceptacion del idioma;
     * cambia el Locale por defecto cambiando asi el idioma de la aplicacion.
     *
     * @param evt (java.awt.event.ActionEvent)
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        String idioma = (String) cmbIdiomas.getSelectedItem();

        if (idioma.equalsIgnoreCase("Galego")) {
            Locale.setDefault(new Locale("gl", "ES"));
        } else {
            Locale.setDefault(new Locale("es", "ES"));
        }

        PaginaPrincipal paginaPrincipal = new PaginaPrincipal();

        if (paginaPrincipal.skCliente != null) {
            paginaPrincipal.setVisible(true);
            
            this.dispose();
        }

        


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorLenguaje().setVisible(true);
            }
        });
    }
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cmbIdiomas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSeleccionaIdioma;

    private void activarAyuda() {
        try {
            URL url = this.getClass().getResource("/ayuda/esp/help.hs");
            HelpSet helpset = new HelpSet(null, url);
            HelpBroker hb = helpset.createHelpBroker();

            hb.enableHelpKey(cmbIdiomas, "seleccionidioma", helpset);
        } catch (HelpSetException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
}
